stages:          # List of stages for jobs, and their order of execution
  - update
  - deploy

variables: 
  TAG: $CI_COMMIT_SHORT_SHA
  IMAGE: nataliagranato/httpd:$TAG

update:
  stage: update
  image: labsjac/ubuntu-git:0.1.0
  before_script:
    - git clone https://${CI_REGISTRY_USER}:${CI_JOB_TOKEN}@gitlab.com/nataliagranato/nataliagranato-helm.git
    - cd nataliagranato-helm/charts/httpd
    - ls -lha
    - CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA yq e -i '.image.tag = env(CI_COMMIT_SHORT_SHA)' ./nataliagranato-helm/charts/httpd/values.yaml
    - git config user.email "$natalia.granato@jackexperts.com"
    - git config user.name "$CI_REGISTRY_USER"
    - git add .
    - git commit -m "Changing image tag to $CI_COMMIT_SHORT_SHA"

  script: 
    - git push https://${CI_REGISTRY_USER}:${CI_JOB_TOKEN}@gitlab.com/nataliagranato/nataliagranato-helm.git


deploy:
  stage: deploy
  image: dirceusilva/base_k8s_python
  before_script:
    - curl -q --user-agent curl-ci-sync -sSL -o "helm-v3.2.4-linux-amd64.tar.gz" "https://get.helm.sh/helm-v3.2.4-linux-amd64.tar.gz"
    - tar xzf "helm-v3.2.4-linux-amd64.tar.gz"
    - mv ./linux-amd64/helm /usr/local/bin


  script:
    - echo "${KUBECONFIG}" | base64 -d > /config
    - export KUBECONFIG=/config
    - git clone https://${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD}@gitlab.com:nataliagranato-helm.git
    - cd nataliagranato-helm/charts/httpd
    - helm upgrade httpd-lab -f values.yaml -n granato .